export interface Camp {
  id: string
  name: string
  age: string
  ageRange: [number, number]
  types: string[]
  displayTypes: string[]
  price: string
  dates: string[]
  description: string
  image: string
}

export const camps: Camp[] = [
  {
    id: 'olymp-kemp',
    name: 'Olymp Kemp',
    age: '8-14 r.',
    ageRange: [8, 14],
    types: ['Náučný', 'Dobrodružný'],
    displayTypes: ['Náučný', 'Dobrodružný'],
    price: '359 €',
    dates: ['1-jul', '2-jul', '1-aug', '2-aug'],
    description: 'Tábor inšpirovaný gréckou mytológiou, ktorý dieťa vtiahne do deja pomocou dobrodružného príbehu. Každý deň spoznáš jedného z gréckych bohov a zahráš si netradičné športové hry. Tak sa priprav na poriadne akčné dobrodružstvo na ktoré nezabudneš!',
    image: '/images/Letne%20Tabory/olympcamp.JPG',
  },
  {
    id: 'fest-animator-fest',
    name: 'Fest Animator Fest',
    age: '13-17 r.',
    ageRange: [13, 17],
    types: ['Tínedžerský', 'Akčný'],
    displayTypes: ['Tínedžerský', 'Akčný'],
    price: '359 €',
    dates: ['1-jul', '2-jul', '1-aug', '2-aug'],
    description: 'Máš 13 rokov a myslíš si, že tábory už nie sú pre teba? Na Feste na rozdiel od ostatných teenage táborov žiadne hry pre malé deti nezažiješ. Diskotéky, splav, športové hry kreatívne aktivity a to najhlavnejšie uvoľnená rodinná atmosféra počas celého týždňa.',
    image: '/images/Letne%20Tabory/fest.JPG',
  },
  {
    id: 'tanecna-planeta',
    name: 'Tanečná Planéta',
    age: '11-16 r.',
    ageRange: [11, 16],
    types: ['Tanečný', 'Umelecký'],
    displayTypes: ['Športový', 'Umelecký'],
    price: '369 €',
    dates: ['1-jul', '1-aug'],
    description: 'Na tomto tábore počas tohto týždňa navštíviš našu Tanečnú planétu. Celý týždeň bude zameraný na workshopy rôznych druhov tanca, popri ktorých si deti budú tvoriť svoje vlastné choreografie, ktoré nakoniec odprezentujú na záverečnom galavečeri.',
    image: '/images/Letne%20Tabory/tanecnaplaneta.JPG',
  },
  {
    id: 'babinec',
    name: 'Babinec',
    age: '10-16 r.',
    ageRange: [10, 16],
    types: ['Unikátny', 'Oddychový', 'Umelecký'],
    displayTypes: ['Unikátny', 'Oddychový'],
    price: '349 €',
    dates: ['1-jul', '2-jul'],
    description: 'Týždeň, počas ktorého môžeš byť presne taká aká si bláznivá, originálna a odvážna. Od workshopov zameraných na vizáž a sebarozvoj až po nekonečné večerné rozhovory pod hviezdami a záverečnú módnu prehliadku. Babinec je proste miesto na ktorom v lete žiadne dievča nesmie chýbať!',
    image: '/images/Letne%20Tabory/babinec.JPG',
  },
  {
    id: 'tajomstvo-basketbaloveho-pohara',
    name: 'Tajomstvo Basketbalového Pohára',
    age: '12-16 r.',
    ageRange: [12, 16],
    types: ['Basketbal', 'Akčný'],
    displayTypes: ['Športový', 'Akčný'],
    price: '369 €',
    dates: ['1-aug'],
    description: 'Vitaj na tábore, kde sa šport spája so zábavou a honbou za tajomstvom. Počas celého tábora ťa čakajú indície, ktoré ťa dovedú až k skrytému poháru, zažiješ ozajstné basketbalové tréningy a vyrobíš si svoj vlastný dres a maskota.',
    image: '/images/Letne%20Tabory/tajomstvopohara.JPG',
  },
  {
    id: 'trhlina',
    name: 'Trhlina',
    age: '10-16 r.',
    ageRange: [10, 16],
    types: ['Akčný', 'Dobrodružný'],
    displayTypes: ['Akčný', 'Dobrodružný'],
    price: '349 €',
    dates: ['1-aug'],
    description: 'Tajomný dobrodružný tábor, kde deti vstúpia do úplne nového sveta plného záhad a prekvapení. Každý deň odhalíš nové tajomstvo a staneš sa súčasťou príbehu, ktorý ťa pohltí od prvej minúty.',
    image: '/images/Letne%20Tabory/trhlina.JPG',
  },
  {
    id: 'ready-player-one',
    name: 'Ready Player One',
    age: '10-16 r.',
    ageRange: [10, 16],
    types: ['Akčný', 'Unikátny', 'Športový'],
    displayTypes: ['Akčný', 'Unikátny'],
    price: '349 €',
    dates: ['2-jul', '2-aug'],
    description: 'Gamer tábor, ktorý nezažiješ doma v izbe. Vstúp do reality svojej obľúbenej počítačovej hry. Na tábore zažiješ najpopulárnejšie počítačové hry a skúsiš si aké je to zahrať si ich v reálnom svete. Tak čo, prijmeš túto výzvu stať sa na týždeň svojou obľúbenou postavou?',
    image: '/images/Letne%20Tabory/readypleayer.JPG',
  },
  {
    id: 'v-dracej-nore',
    name: 'V Dracej Nore',
    age: '10-14 r.',
    ageRange: [10, 14],
    types: ['Fantasy', 'Dobrodružný'],
    displayTypes: ['Fantasy', 'Dobrodružný'],
    price: '349 €',
    dates: ['1-aug'],
    description: 'Dobrodružný fantasy tábor inšpirovaný hrou D&D na ktorom fantázia nepozná hranice a z detí stávajú hrdinovia. Každé dieťa si vytvorí svoju vlastnú postavu, za ktorú bude hrať celý týždeň. Príbeh vtiahne dieťa ktoré sa v ňom rozhoduje podľa seba a prežije tak veľkolepé dobrodružstvo na ktoré nikdy nezabudne!',
    image: '/images/Letne%20Tabory/V-dracej-nore.JPG',
  },
  {
    id: 'anglicke-leto',
    name: 'Summer Advanture',
    age: '8-12 r.',
    ageRange: [8, 12],
    types: ['Oddychový', 'Náučný'],
    displayTypes: ['Oddychový', 'Náučný'],
    price: '369 €',
    dates: ['1-jul'],
    description: 'Zaži autentický jazykový zážitok v angličtine bez učebníc, učenia a stresu. Summer Adventure buduje pozitívny vzťah k jazyku bez nátlaku. Na tábore zažiješ nezvyčajné aktivity, ktoré podporujú učenie jazyka hravou formou.',
    image: '/images/Letne%20Tabory/summeradvatnure.JPG',
  },
  {
    id: 'neverfort',
    name: 'Neverfort',
    age: '10-16 r.',
    ageRange: [10, 16],
    types: ['Akčný', 'Fantasy'],
    displayTypes: ['Akčný', 'Fantasy'],
    price: '349 €',
    dates: ['1-aug'],
    description: 'Tajomný tábor, kde sa stretávajú dva mystické svety… Wednesday a Harry Potter. Na jednom mieste sa stretnú čarodejníci, škriatkovia, upíri, vlkodlaci, sirény, gorgony a spoločne objavia kúzla, veštenie a elixíry. Príbeh zažiješ z prvej ruky a staneš sa jeho aktívnou súčasťou!',
    image: '/images/Letne%20Tabory/neverfot.JPG',
  },
  {
    id: 'chlapinec',
    name: 'Chlapinec',
    age: '10-16 r.',
    ageRange: [10, 16],
    types: ['Akčný', 'Náučný'],
    displayTypes: ['Akčný', 'Náučný'],
    price: '349 €',
    dates: ['1-jul', '2-jul'],
    description: 'Tábor na ktorom si chlapci osvoja dôležité zručnosti a stanú sa súčasťou pravej chlapskej partie. Od stavania príbytkov v lese až po splav Váhu na pltiach chlapinec je jediný tábor svojho druhu.',
    image: '/images/Letne%20Tabory/chlapinec.JPG',
  },
  {
    id: 'artlantida',
    name: 'Artlantída',
    age: '11-17 r.',
    ageRange: [11, 17],
    types: ['Umelecký', 'Oddychový'],
    displayTypes: ['Umelecký', 'Oddychový'],
    price: '349 €',
    dates: ['1-jul', '2-jul'],
    description: 'Umelecký tábor pre deti, ktoré chcú tvoriť, myslieť a byť samy sebou. Vaše dieťa zažije týždeň plný kreativity a zábavy popri ktorej sa niečo nové naučí a odnesie si domov výtvory ktoré mu ostanú navždy.',
    image: '/images/Letne%20Tabory/Art.JPG',
  },
  {
    id: 'stastna-plutva',
    name: 'Šťastná Plutva',
    age: '6-10 r.',
    ageRange: [6, 10],
    types: ['Oddychový'],
    displayTypes: ['Oddychový'],
    price: '349 €',
    dates: ['1-aug'],
    description: 'Podmorské dobrodružstvo pre najmenších, ktoré prináša prvé kroky k samostatnosti zabalené do veľkého príbehu. Deti vstúpia do sveta Nema a Dori, trávia veľa času v bazéne a pri vode a popri tom objavujú nové postavy a odhaľujú príbeh.',
    image: '/images/Letne%20Tabory/plutva.JPG',
  },
  {
    id: 'kazdy-den-novy-zazitok',
    name: 'Každý Deň Nový Zážitok',
    age: '8-14 r.',
    ageRange: [8, 14],
    types: ['Dobrodružný', 'Umelecký'],
    displayTypes: ['Dobrodružný', 'Umelecký'],
    price: '359 €',
    dates: ['2-jul', '1-aug'],
    description: 'Vyskúšaj si aké je to byť cowboyom, pirátom, detektívom alebo indiánom. Myslíš, že sa to nedá stihnúť za jeden týždeň? To je asi pravda ale na KDNZ je možné všetko. Každý deň ťa prevedie iným svetom z ktorého si odnesieš svoj vlastný suvenír.',
    image: '/images/Letne%20Tabory/kazdydennovyzazitok.JPG',
  },
  {
    id: 'z-bodu-nula-do-bodu-sto',
    name: 'Z Bombova Do Bombova',
    age: '8-14 r.',
    ageRange: [8, 14],
    types: ['Oddychový', 'Unikátny'],
    displayTypes: ['Oddychový', 'Unikátny'],
    price: '369 €',
    dates: ['1-jul', '1-aug'],
    description: 'Pohodový tábor plný hier z každého súdku. Počas týždňa zažiješ ideálny mix pohybu, kreativity a oddychu. Zasúťažíš si v rôznych hrách, potrápiš svoje myslenie, oddýchneš si pri opekačke a dokonca si aj niečo vyrobíš.',
    image: '/images/Letne%20Tabory/zbombova-do-bombova.JPG',
  },
  {
    id: 'woodkemp',
    name: 'WoodKemp',
    age: '9-16 r.',
    ageRange: [9, 16],
    types: ['Akčný', 'Náučný'],
    displayTypes: ['Akčný', 'Náučný'],
    price: '359 €',
    dates: ['2-jul', '1-aug'],
    description: 'Uži si týždeň plný stavania bunkrov v lese, strategických hier, pobytu v prírode a nefalšovanej zábavy. Tradičné táborové prostredie, opekačka, vyrábanie vecí z dreva a to všetko s tou najlepšou partiou. Ak chceš v lete zažiť skutočné zážitky, na tomto tábore nesmieš chýbať!',
    image: '/images/Letne%20Tabory/woodcamp.JPG',
  },
  {
    id: 'expecto',
    name: 'Expecto',
    age: '10-16 r.',
    ageRange: [10, 16],
    types: ['Dobrodružný', 'Fantasy'],
    displayTypes: ['Dobrodružný', 'Fantasy'],
    price: '349 €',
    dates: ['1-jul'],
    description: 'Ponor sa do fantastického sveta mágie a zaži tak príbeh čarodejníka na vlastnej koži. Staň sa majstrom v čarodejníckych dueloch, spoznávaj magické tvory a odhaľuj rôzne tajomstvá. Vstúp s nami do sveta kúziel a buď súčasťou dobrodružstva ktoré len tak nezažiješ!',
    image: '/images/Letne%20Tabory/expcto.JPG',
  },
]
